spring:
  datasource:
    hikari:
      batch:
        jdbc-url: jdbc:mysql://localhost:3306/batch
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 1234
      demo:
        jdbc-url: jdbc:mysql://localhost:3306/demo??rewriteBatchedStatements=true
        driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: 1234
  batch:
    initialize-schema: always
    job:
      names: ${job.name:createArticleStep}
    schema: schema-mysql.sql
    table-prefix: batch.BATCH_
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy:org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
logging:
  level:
    root: info
    org.springframework.jdbc.core: DEBUG